"""
Nudge Schema

Proactive suggestions/prompts generated by the Mind.
"""

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, Field

from sxth_mind._time import utcnow


class Nudge(BaseModel):
    """
    A proactive nudge/suggestion for the user.

    Nudges are generated based on patterns, inactivity, or
    opportunities detected by the Mind.
    """

    id: str = Field(default="", description="Unique identifier")
    project_mind_id: str = Field(..., description="Reference to ProjectMind")

    # Nudge content
    nudge_type: str = Field(..., description="Type of nudge (from adapter templates)")
    title: str = Field(..., description="Short headline")
    message: str = Field(..., description="Full nudge message")

    # Priority and timing
    priority: int = Field(
        default=5,
        ge=1,
        le=10,
        description="Priority 1-10 (higher = more important)",
    )
    scheduled_for: datetime | None = Field(
        default=None,
        description="When to deliver (None = immediate)",
    )

    # State
    status: Literal["pending", "delivered", "dismissed", "acted"] = Field(
        default="pending",
        description="Nudge status",
    )
    delivered_at: datetime | None = Field(default=None)
    dismissed_at: datetime | None = Field(default=None)
    acted_at: datetime | None = Field(default=None)

    # Context
    context: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional context for the nudge",
    )

    # Timestamps
    created_at: datetime = Field(default_factory=utcnow)
    updated_at: datetime = Field(default_factory=utcnow)

    model_config = {"extra": "allow"}

    def deliver(self) -> None:
        """Mark nudge as delivered."""
        self.status = "delivered"
        self.delivered_at = utcnow()
        self.updated_at = utcnow()

    def dismiss(self) -> None:
        """Mark nudge as dismissed."""
        self.status = "dismissed"
        self.dismissed_at = utcnow()
        self.updated_at = utcnow()

    def mark_acted(self) -> None:
        """Mark nudge as acted upon."""
        self.status = "acted"
        self.acted_at = utcnow()
        self.updated_at = utcnow()

    def set_status(self, status: str) -> None:
        """Set status, recording the matching timestamp for known transitions."""
        if status == "delivered":
            self.deliver()
        elif status == "dismissed":
            self.dismiss()
        elif status == "acted":
            self.mark_acted()
        else:
            self.status = status  # type: ignore[assignment]
            self.updated_at = utcnow()
